## what is Pytorch

![picture](https://cdn.analyticsvidhya.com/wp-content/uploads/2019/09/pytorch.png)

PyTorch is a Python-based library used to build neural networks.

It provides classes that allow us to easily develop a suite of deep learning models.

It gives maximum flexibility and speed.

## Install pytorch

In [ ]:
# !conda install pytorch torchvision -c pytorch
# # or with GPU
# ! conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

#https://pytorch.org/

###Let's import pytorch and check that it's well installed

In [ ]:
import torch
print(torch.__version__)

1.13.1+cu116


## Tensors

At its core, PyTorch is a library for processing tensors. Tensors are multidimensional arrays. And PyTorch tensors are similar to NumPy’s n-dimensional arrays. We can use these tensors on a GPU as well (this is not the case with NumPy arrays). This is a major advantage of using tensors. A tensor can be a number, vector, matrix, or any n-dimensional array

PyTorch supports multiple types of tensors, including:

1. FloatTensor: 32-bit float
2. DoubleTensor: 64-bit float
3. HalfTensor: 16-bit float
4. IntTensor: 32-bit int
5. LongTensor: 64-bit int








Let's create a tensor with a single number.

In [ ]:
# Number
t1 = torch.tensor(4.)
print(t1.dtype)
print(t1)
print(t1.shape)

torch.float32
tensor(4.)
torch.Size([])


In [ ]:
# 1d tensor(vector)
t2 = torch.tensor([1., 2, 3, 4])
print(t2)
print(t2.shape)

tensor([1., 2., 3., 4.])
torch.Size([4])


In [ ]:
# 2d tensor or matrix

# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])

print(t3)
print(t3.shape)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.Size([3, 2])


In [ ]:
#3d tensor
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print(t4)
print(t4.shape)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])
torch.Size([2, 2, 3])


In [ ]:
t5 = torch.tensor([[2,4 ,5],[2, 4, 5]])
print(t5)

tensor([[2, 4, 5],
        [2, 4, 5]])


## Mathematical operations on tensors

In [ ]:
a =  torch.tensor([1., 2, 3, 4])
b =  torch.tensor([5., 6, 7, 8])

print("===========sum of a and b=============")

print(a + b)
print()
print("===========substracting a from b======")

print(b - a)
print()

print("===========multiplying a and b=========")

print(a * b)
print()
print("===========dividing b per a=============")

print(b/a)

===========sum of a and b=============
tensor([ 6.,  8., 10., 12.])

===========substracting a from b======
tensor([4., 4., 4., 4.])

===========multiplying a and b=========
tensor([ 5., 12., 21., 32.])

===========dividing b per a=============
tensor([5.0000, 3.0000, 2.3333, 2.0000])


## Matrix Initialization

### Create  a matrix of shape 3*3 having all zeros

In [ ]:
a1= torch.zeros((3,3))
a1.shape

torch.Size([3, 3])

### Create  a matrix of shape 3*3 having all ones

In [ ]:
a2 = torch.ones((3,3))
a2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## create  a 3x3 matrix randomly filled

In [ ]:
# setting the random seed for pytorch
torch.manual_seed(42)
#torch.manual_seed(42)
# matrix of random numbers
## torch.randn returns a tensor filled with random numbers from a normal distribution with mean `0` and variance `1`
torch.rand(3,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [ ]:
# torch.randint returns a tensor filled with random integers generated uniformly
torch.randint(0, 10,(3,3))

tensor([[3, 8, 4],
        [0, 4, 1],
        [2, 5, 5]])

In [ ]:
## torch.rand returns a tensor filled with random numbers from a uniform distribution on the interval `[0, 1)`
torch.rand(3,3)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

## Torch tensors and numpy conversion

In [ ]:
## Tensor to numpy array
a = torch.rand(3,3)
print(a)
## convert a into numpy array b
b= a.numpy()
## update the tensor a by adding a value to it
print(b)
##print b
a+=2
b= a.numpy()
print(b)

tensor([[0.0162, 0.2137, 0.6249],
        [0.4340, 0.1371, 0.5117],
        [0.1585, 0.0758, 0.2247]])
[[0.01620269 0.21366489 0.62490183]
 [0.4340034  0.137057   0.51172835]
 [0.15845925 0.07580167 0.22466868]]
[[2.0162027 2.213665  2.6249018]
 [2.4340034 2.137057  2.5117283]
 [2.1584592 2.0758016 2.2246687]]


In [ ]:
## Numpy array to tensor
import numpy as np

a = np.random.rand(3,3)
print(a)
## convert array a into tensor b
b = torch.from_numpy(a).clone()
print(b)
a+=2
print(b)

[[0.45071084 0.91712616 0.95031086]
 [0.8334643  0.31198185 0.77571418]
 [0.31464454 0.7961014  0.0048962 ]]
tensor([[0.4507, 0.9171, 0.9503],
        [0.8335, 0.3120, 0.7757],
        [0.3146, 0.7961, 0.0049]], dtype=torch.float64)
tensor([[0.4507, 0.9171, 0.9503],
        [0.8335, 0.3120, 0.7757],
        [0.3146, 0.7961, 0.0049]], dtype=torch.float64)


## Matrix operations

In [ ]:
torch.manual_seed(0)
a = torch.randn(3,3)

b = torch.randn(3,3)
print(a)
print(b)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])
tensor([[-0.4033, -0.5966,  0.1820],
        [-0.8567,  1.1006, -1.0712],
        [ 0.1227, -0.5663,  0.3731]])


For addition, substraction and division we can either use torch.add, torch.sub, torch.div or +,  - and /

In [ ]:
## compute sum of a and b
print(a + b)

tensor([[ 1.1377, -0.8901, -1.9968],
        [-0.2882,  0.0161, -2.4698],
        [ 0.5260,  0.2717, -0.3461]])


In [ ]:
torch.add(a,b)

tensor([[ 1.1377, -0.8901, -1.9968],
        [-0.2882,  0.0161, -2.4698],
        [ 0.5260,  0.2717, -0.3461]])

In [ ]:
torch.sub(a,b)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])

In [ ]:
## compute a -b
print(a-b)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])


In [ ]:
##compute a / b
print(a/b)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [ ]:
torch.div(a, b)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])

In [ ]:
torch.sum(b, dim=0)

tensor([2.3356, 0.1672, 0.6376])

## Multiplication

### Elementwise multiplication

In [ ]:
a * b


tensor([[ 0.0900,  0.0689,  0.1898],
        [ 0.2557,  1.8974,  0.1843],
        [ 2.1154, -0.8435,  0.3773]])

### matrix multiplication

In [ ]:
##using torch.mm
torch.mm(a,b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [ ]:
##using torch.matmul
torch.matmul(a,b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [ ]:
##using @
a@b

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

## Reshape, Transpose and concatenate tensors

In [ ]:
torch.manual_seed(42)
a = torch.randn(3,4)
print(a.shape)
b = a.reshape(-1, 1)
print(b.shape)
c = a.reshape(6,2)
print(c.shape)

torch.Size([3, 4])
torch.Size([12, 1])
torch.Size([6, 2])


In [ ]:
a_t = torch.t(a)
print(a_t.shape)

torch.Size([4, 3])


In [ ]:
print(a.T.shape)

torch.Size([4, 3])


In [ ]:
b = torch.randn(1, 4)
print(b.shape)
concat = torch.cat((a, b), dim=0)
print(concat.shape)

torch.Size([1, 4])
torch.Size([4, 4])


In [ ]:
flat_vect = a.flatten()
print(flat_vect)
flat_vect.shape

tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
         0.4617,  0.2674,  0.5349,  0.8094])


torch.Size([12])

## Extra reading

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html
